spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_ride
    username: sam
    password: sam
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format-sql: true

server:
  port: 8081
